name: Lawis-Windows

on:
  workflow_dispatch:
    inputs:
      authcode:
        description: 'CDR BAŞLATMA KODU'
        required: true
      pincode:
        description: '6 HANELİ ŞİFRE'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Initializing Setup
      run: ./setup.ps1
    - name: Starting CRD 
      run: ${{ github.event.inputs.authcode }} -pin=${{ github.event.inputs.pincode }}
    - name: Keep Alive
      run: ./timeout.ps1

  display-actions-url:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Display Actions URL
      run: echo "Actions URL: ${{ github.run_url }}"
      
